#pragma once

#ifndef __MainWnd__
#define __MainWnd__

/**
@file
Subclass of IMainWnd, which is generated by wxFormBuilder.
*/

#include "wxUI.h"

//// end generated include

/** Implementing IMainWnd */
class xMainWnd : public ui::IMainWnd {
public:
	using this_t = xMainWnd;
	using base_t = ui::IMainWnd;

protected:
	bool m_bInitialized{};

public:
	/** Constructor */
	xMainWnd(wxWindow* parent);
//// end generated class members

protected:
	virtual void OnMove( wxMoveEvent& event ) override;
	virtual void OnSize( wxSizeEvent& event ) override;

	virtual void OnButtonClick_Go( wxCommandEvent& event ) override;
	virtual void OnDirctrlSelectionChanged( wxCommandEvent& event ) override;
};

#endif // __MainWnd__
