#ifndef __IDlgMatViewOption__
#define __IDlgMatViewOption__

/**
@file
Subclass of IDlgMatViewOption, which is generated by wxFormBuilder.
*/

#include "wxMatView.h"

//// end generated include

/** Implementing IDlgMatViewOption */
class xDlgMatViewOption : public ui::IDlgMatViewOption {
public:
	using this_t = xDlgMatViewOption;
	using base_t = ui::IDlgMatViewOption;
public:
	/** Constructor */
	xDlgMatViewOption(xMatView::S_OPTION const& option, wxWindow* parent);

	xMatView::S_OPTION m_option;

protected:
	// Handlers for IDlgMatViewOption events.
	virtual void OnCheckBox_Skia( wxCommandEvent& event ) override;
	virtual void OnButtonClick_RestoreBackgroundColor(wxCommandEvent& event) override;
	virtual void OnButtonClick_OK( wxCommandEvent& event ) override;
	virtual void OnButtonClick_Cancel( wxCommandEvent& event ) override;

//// end generated class members
};

#endif // __IDlgMatViewOption__
